name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  static_secrets:
    runs-on: self-hosted
    permissions: 
      id-token: write
      contents: read    
    name: Fetch static secrets
    steps:
    - name: Fetch secrets from aKeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3
      with:
        access-id: ${{ secrets.ACCESS_ID }}
        api-url: 'https://cm.jmendeztech.click/akeyless-api'
        #access-type: 'aws_iam'
        static-secrets: '{"/springbootdeploy/ssh-privatekey":"PRIVATE_KEY"}'

    - name: Use Outputs
      run: |
        echo "PRIVATE_KEY: ${{ steps.fetch-secrets.outputs.PRIVATE_KEY }}"
