name: CI/CD Pipeline
on: push
     
jobs:
  static_secrets:
    runs-on: self-hosted
    name: Fetch static secrets
    
    permissions: 
      id-token: write
      contents: read    

    steps:
    - name: Fetch secrets from aKeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3.1.1
      with:
        access-id: ${{ secrets.ACCESS_ID }}
        #api-url: 'https://cm.jmendeztech.click/akeyless-api'
        #access-type: 'aws_iam'
        static-secrets: '{"/springbootdeploy/SSH-PRIVATE-KEY":"PRIVATE_KEY"}'

    - name: Use Outputs
      run: |
        echo "PRIVATE_KEY: ${{ steps.fetch-secrets.outputs.PRIVATE_KEY }}"
